// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// A single token event emitted during streaming generation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MlxTokenEvent {
  /// The generated token text (may be empty when isDone = true).
  var token: String
  /// True when generation is complete.
  var isDone: Bool
  /// Current tokens/sec rate, reported with every token.
  var tokensPerSecond: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MlxTokenEvent? {
    let token = pigeonVar_list[0] as! String
    let isDone = pigeonVar_list[1] as! Bool
    let tokensPerSecond: Double? = nilOrValue(pigeonVar_list[2])

    return MlxTokenEvent(
      token: token,
      isDone: isDone,
      tokensPerSecond: tokensPerSecond
    )
  }
  func toList() -> [Any?] {
    return [
      token,
      isDone,
      tokensPerSecond,
    ]
  }
}

/// A single chat message for the conversation context.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MlxChatMessage {
  /// "system" | "user" | "assistant"
  var role: String
  var content: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MlxChatMessage? {
    let role = pigeonVar_list[0] as! String
    let content = pigeonVar_list[1] as! String

    return MlxChatMessage(
      role: role,
      content: content
    )
  }
  func toList() -> [Any?] {
    return [
      role,
      content,
    ]
  }
}

/// Generation hyper-parameters.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MlxGenerationParams {
  var temperature: Double
  var topP: Double
  var maxTokens: Int64
  var seed: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MlxGenerationParams? {
    let temperature = pigeonVar_list[0] as! Double
    let topP = pigeonVar_list[1] as! Double
    let maxTokens = pigeonVar_list[2] as! Int64
    let seed: Int64? = nilOrValue(pigeonVar_list[3])

    return MlxGenerationParams(
      temperature: temperature,
      topP: topP,
      maxTokens: maxTokens,
      seed: seed
    )
  }
  func toList() -> [Any?] {
    return [
      temperature,
      topP,
      maxTokens,
      seed,
    ]
  }
}

private class MlxInferencePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MlxTokenEvent.fromList(self.readValue() as! [Any?])
    case 130:
      return MlxChatMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return MlxGenerationParams.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MlxInferencePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MlxTokenEvent {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? MlxChatMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? MlxGenerationParams {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MlxInferencePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MlxInferencePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MlxInferencePigeonCodecWriter(data: data)
  }
}

class MlxInferencePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MlxInferencePigeonCodec(readerWriter: MlxInferencePigeonCodecReaderWriter())
}

var mlxInferencePigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MlxInferencePigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MlxInferenceHostApi {
  /// Load the model from a local directory path.
  /// The model must already be downloaded to [localPath].
  func loadModel(localPath: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Start a streaming generation pass.
  /// Tokens arrive via [MlxTokenStreamApi].
  func startGeneration(messages: [MlxChatMessage], params: MlxGenerationParams) throws
  /// Cancel an in-flight generation.
  func cancelGeneration() throws
  /// Release the loaded model and free memory.
  func disposeModel() throws
  /// Returns true if a model is currently loaded.
  func isModelLoaded() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MlxInferenceHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MlxInferencePigeonCodec.shared }
  /// Sets up an instance of `MlxInferenceHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MlxInferenceHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Load the model from a local directory path.
    /// The model must already be downloaded to [localPath].
    let loadModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.little_star_app.MlxInferenceHostApi.loadModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localPathArg = args[0] as! String
        api.loadModel(localPath: localPathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadModelChannel.setMessageHandler(nil)
    }
    /// Start a streaming generation pass.
    /// Tokens arrive via [MlxTokenStreamApi].
    let startGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.little_star_app.MlxInferenceHostApi.startGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startGenerationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messagesArg = args[0] as! [MlxChatMessage]
        let paramsArg = args[1] as! MlxGenerationParams
        do {
          try api.startGeneration(messages: messagesArg, params: paramsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startGenerationChannel.setMessageHandler(nil)
    }
    /// Cancel an in-flight generation.
    let cancelGenerationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.little_star_app.MlxInferenceHostApi.cancelGeneration\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelGenerationChannel.setMessageHandler { _, reply in
        do {
          try api.cancelGeneration()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelGenerationChannel.setMessageHandler(nil)
    }
    /// Release the loaded model and free memory.
    let disposeModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.little_star_app.MlxInferenceHostApi.disposeModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeModelChannel.setMessageHandler { _, reply in
        do {
          try api.disposeModel()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeModelChannel.setMessageHandler(nil)
    }
    /// Returns true if a model is currently loaded.
    let isModelLoadedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.little_star_app.MlxInferenceHostApi.isModelLoaded\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isModelLoadedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isModelLoaded()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isModelLoadedChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class OnTokenStreamHandler: PigeonEventChannelWrapper<MlxTokenEvent> {
  static func register(with messenger: FlutterBinaryMessenger, 
                      instanceName: String = "",
                      streamHandler: OnTokenStreamHandler) {
    var channelName = "dev.flutter.pigeon.little_star_app.MlxTokenStreamApi.onToken"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<MlxTokenEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: mlxInferencePigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
