// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// A single token event emitted during streaming generation.
class MlxTokenEvent {
  MlxTokenEvent({
    required this.token,
    required this.isDone,
    this.tokensPerSecond,
  });

  /// The generated token text (may be empty when isDone = true).
  String token;

  /// True when generation is complete.
  bool isDone;

  /// Current tokens/sec rate, reported with every token.
  double? tokensPerSecond;

  Object encode() {
    return <Object?>[
      token,
      isDone,
      tokensPerSecond,
    ];
  }

  static MlxTokenEvent decode(Object result) {
    result as List<Object?>;
    return MlxTokenEvent(
      token: result[0]! as String,
      isDone: result[1]! as bool,
      tokensPerSecond: result[2] as double?,
    );
  }
}

/// A single chat message for the conversation context.
class MlxChatMessage {
  MlxChatMessage({
    required this.role,
    required this.content,
  });

  /// "system" | "user" | "assistant"
  String role;

  String content;

  Object encode() {
    return <Object?>[
      role,
      content,
    ];
  }

  static MlxChatMessage decode(Object result) {
    result as List<Object?>;
    return MlxChatMessage(
      role: result[0]! as String,
      content: result[1]! as String,
    );
  }
}

/// Generation hyper-parameters.
class MlxGenerationParams {
  MlxGenerationParams({
    this.temperature = 0.6,
    this.topP = 0.9,
    this.maxTokens = 512,
    this.seed,
  });

  double temperature;

  double topP;

  int maxTokens;

  int? seed;

  Object encode() {
    return <Object?>[
      temperature,
      topP,
      maxTokens,
      seed,
    ];
  }

  static MlxGenerationParams decode(Object result) {
    result as List<Object?>;
    return MlxGenerationParams(
      temperature: result[0]! as double,
      topP: result[1]! as double,
      maxTokens: result[2]! as int,
      seed: result[3] as int?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is MlxTokenEvent) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is MlxChatMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is MlxGenerationParams) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return MlxTokenEvent.decode(readValue(buffer)!);
      case 130: 
        return MlxChatMessage.decode(readValue(buffer)!);
      case 131: 
        return MlxGenerationParams.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class MlxInferenceHostApi {
  /// Constructor for [MlxInferenceHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MlxInferenceHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Load the model from a local directory path.
  /// The model must already be downloaded to [localPath].
  Future<void> loadModel(String localPath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.little_star_app.MlxInferenceHostApi.loadModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[localPath]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Start a streaming generation pass.
  /// Tokens arrive via [MlxTokenStreamApi].
  Future<void> startGeneration(List<MlxChatMessage> messages, MlxGenerationParams params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.little_star_app.MlxInferenceHostApi.startGeneration$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[messages, params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Cancel an in-flight generation.
  Future<void> cancelGeneration() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.little_star_app.MlxInferenceHostApi.cancelGeneration$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Release the loaded model and free memory.
  Future<void> disposeModel() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.little_star_app.MlxInferenceHostApi.disposeModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Returns true if a model is currently loaded.
  Future<bool> isModelLoaded() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.little_star_app.MlxInferenceHostApi.isModelLoaded$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

Stream<MlxTokenEvent> onToken( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  const EventChannel onTokenChannel =
      EventChannel('dev.flutter.pigeon.little_star_app.MlxTokenStreamApi.onToken', pigeonMethodCodec);
  return onTokenChannel.receiveBroadcastStream().map((dynamic event) {
    return event as MlxTokenEvent;
  });
}
    
