// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Normalized thermal pressure level, collapsing each platform's native scale
/// (iOS: 4 levels; Android: 7 levels, API 29+) onto a shared 4-point scale so
/// benchmark output is comparable across backends/devices.
enum ThermalStatus: Int {
  case nominal = 0
  case fair = 1
  case serious = 2
  case critical = 3
  /// Reading unavailable — e.g. Android below API 29, or the platform call
  /// failed. Callers should treat this as "unknown", not "nominal".
  case unknown = 4
}

private class DeviceTelemetryPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ThermalStatus(rawValue: enumResultAsInt)
      }
      return nil
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DeviceTelemetryPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ThermalStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class DeviceTelemetryPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DeviceTelemetryPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DeviceTelemetryPigeonCodecWriter(data: data)
  }
}

class DeviceTelemetryPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DeviceTelemetryPigeonCodec(readerWriter: DeviceTelemetryPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeviceTelemetryHostApi {
  /// Current thermal pressure state.
  /// iOS: `ProcessInfo.processInfo.thermalState`.
  /// Android: `PowerManager.getCurrentThermalStatus()` (API 29+; returns
  /// [ThermalStatus.unknown] below API 29).
  func getThermalState() throws -> ThermalStatus
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DeviceTelemetryHostApiSetup {
  static var codec: FlutterStandardMessageCodec { DeviceTelemetryPigeonCodec.shared }
  /// Sets up an instance of `DeviceTelemetryHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DeviceTelemetryHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Current thermal pressure state.
    /// iOS: `ProcessInfo.processInfo.thermalState`.
    /// Android: `PowerManager.getCurrentThermalStatus()` (API 29+; returns
    /// [ThermalStatus.unknown] below API 29).
    let getThermalStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.little_star_app.DeviceTelemetryHostApi.getThermalState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getThermalStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getThermalState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getThermalStateChannel.setMessageHandler(nil)
    }
  }
}
