// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package tw.twinkleai.little_star_app

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Normalized thermal pressure level, collapsing each platform's native scale
 * (iOS: 4 levels; Android: 7 levels, API 29+) onto a shared 4-point scale so
 * benchmark output is comparable across backends/devices.
 */
enum class ThermalStatus(val raw: Int) {
  NOMINAL(0),
  FAIR(1),
  SERIOUS(2),
  CRITICAL(3),
  /**
   * Reading unavailable — e.g. Android below API 29, or the platform call
   * failed. Callers should treat this as "unknown", not "nominal".
   */
  UNKNOWN(4);

  companion object {
    fun ofRaw(raw: Int): ThermalStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}
private open class DeviceTelemetryPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ThermalStatus.ofRaw(it.toInt())
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ThermalStatus -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DeviceTelemetryHostApi {
  /**
   * Current thermal pressure state.
   * iOS: `ProcessInfo.processInfo.thermalState`.
   * Android: `PowerManager.getCurrentThermalStatus()` (API 29+; returns
   * [ThermalStatus.unknown] below API 29).
   */
  fun getThermalState(): ThermalStatus

  companion object {
    /** The codec used by DeviceTelemetryHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      DeviceTelemetryPigeonCodec()
    }
    /** Sets up an instance of `DeviceTelemetryHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DeviceTelemetryHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.little_star_app.DeviceTelemetryHostApi.getThermalState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getThermalState())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
